// Compile-time embedding of execution assets only. Decision documents (`SKILL.md`) and legacy
// script packs are website/history inputs and must never affect the CLI build. The live target probe
// and schemas remain mechanism inputs.
use std::fs;
use std::io::Write;
use std::path::{Path, PathBuf};

fn collect(dir: &Path, root: &Path, out: &mut Vec<(String, PathBuf)>) {
    let mut entries: Vec<_> = fs::read_dir(dir)
        .unwrap_or_else(|e| panic!("read {}: {e}", dir.display()))
        .filter_map(|e| e.ok())
        .map(|e| e.path())
        .collect();
    entries.sort(); // deterministic order → reproducible embedded_assets.rs
    for path in entries {
        if path.is_dir() {
            collect(&path, root, out);
        } else if path.is_file() {
            let rel = path
                .strip_prefix(root)
                .expect("under root")
                .to_string_lossy()
                .replace('\\', "/");
            if rel.ends_with(".schema.json") {
                out.push((rel, path));
            }
        }
    }
}

fn main() {
    let manifest_dir = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").unwrap());
    let mut files = Vec::new();
    let probe = manifest_dir.join("ouro-skills/lib/ouro-probe.sh");
    if !probe.is_file() {
        panic!("missing typed target probe {}", probe.display());
    }
    files.push(("lib/ouro-probe.sh".to_string(), probe));

    // Also embed the pool-spec JSON schema (lives at repo-root schemas/, outside ouro-skills/)
    // so the bundle manifest's schema_hash is meaningful and the binary can self-describe the
    // spec contract it validates against (rel keys keep their `schemas/` prefix).
    let schemas_root = manifest_dir.join("schemas");
    if schemas_root.is_dir() {
        collect(&schemas_root, &manifest_dir, &mut files);
    }
    for (_, path) in &files {
        println!("cargo:rerun-if-changed={}", path.display());
    }

    let out_dir = PathBuf::from(std::env::var("OUT_DIR").unwrap());

    // S0020 p1-2 — the control release carries the target-architecture runner. Building the Linux
    // runner itself leaves this file empty; the subsequent macOS control build points the private
    // build input at that repository-built artifact. The path is a build input, never a public CLI
    // parameter, so an agent cannot select arbitrary executable bytes for target dispatch.
    println!("cargo:rerun-if-env-changed=OURO_EMBED_LINUX_X86_64_RUNNER");
    let runner_dest = out_dir.join("ephemeral_linux_x86_64_runner.bin");
    match std::env::var_os("OURO_EMBED_LINUX_X86_64_RUNNER") {
        Some(source) => {
            let source = PathBuf::from(source);
            println!("cargo:rerun-if-changed={}", source.display());
            fs::copy(&source, &runner_dest).unwrap_or_else(|error| {
                panic!(
                    "copy Linux/x86_64 runner {} to {}: {error}",
                    source.display(),
                    runner_dest.display()
                )
            });
        }
        None => fs::write(&runner_dest, []).expect("create empty runner build input"),
    }

    let dest = out_dir.join("embedded_assets.rs");
    let mut f = fs::File::create(&dest).expect("create embedded_assets.rs");
    writeln!(
        f,
        "// @generated by build.rs — do not edit. {} embedded execution assets.",
        files.len()
    )
    .unwrap();
    writeln!(f, "pub static EMBEDDED: &[(&str, &[u8])] = &[").unwrap();
    for (rel, abs) in &files {
        // include_bytes! with an absolute path — no escaping of file contents needed.
        writeln!(
            f,
            "    ({:?}, include_bytes!({:?})),",
            rel,
            abs.to_string_lossy()
        )
        .unwrap();
    }
    writeln!(f, "];").unwrap();
}
