// S0016 p2-1 — compile-time embedding of ouro-skills/ into the binary.
// Walks ouro-skills/ and generates $OUT_DIR/embedded_skills.rs holding a static slice of
// (relative-path, &[u8]) via include_bytes!. The installed single binary therefore carries
// its own decision docs (SKILL.md, p2-7 `ouro skill show`) and mechanism scripts
// (scripts/*.sh, lib/*.sh) — no external fetch, no on-disk skills required at runtime.
use std::fs;
use std::io::Write;
use std::path::{Path, PathBuf};

fn collect(dir: &Path, root: &Path, out: &mut Vec<(String, PathBuf)>) {
    let mut entries: Vec<_> = fs::read_dir(dir)
        .unwrap_or_else(|e| panic!("read {}: {e}", dir.display()))
        .filter_map(|e| e.ok())
        .map(|e| e.path())
        .collect();
    entries.sort(); // deterministic order → reproducible embedded_skills.rs
    for path in entries {
        if path.is_dir() {
            collect(&path, root, out);
        } else if path.is_file() {
            let rel = path
                .strip_prefix(root)
                .expect("under root")
                .to_string_lossy()
                .replace('\\', "/");
            // Only embed the asset kinds the runtime needs: decision docs and shell assets.
            if rel.ends_with("/SKILL.md")
                || rel.ends_with(".sh")
                || rel.ends_with(".schema.json")
            {
                out.push((rel, path));
            }
        }
    }
}

fn main() {
    let manifest_dir = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").unwrap());
    let skills_root = manifest_dir.join("ouro-skills");
    println!("cargo:rerun-if-changed=ouro-skills");

    let mut files = Vec::new();
    collect(&skills_root, &skills_root, &mut files);

    // Also embed the pool-spec JSON schema (lives at repo-root schemas/, outside ouro-skills/)
    // so the bundle manifest's schema_hash is meaningful and the binary can self-describe the
    // spec contract it validates against (rel keys keep their `schemas/` prefix).
    let schemas_root = manifest_dir.join("schemas");
    if schemas_root.is_dir() {
        println!("cargo:rerun-if-changed=schemas");
        collect(&schemas_root, &manifest_dir, &mut files);
    }

    let out_dir = PathBuf::from(std::env::var("OUT_DIR").unwrap());
    let dest = out_dir.join("embedded_skills.rs");
    let mut f = fs::File::create(&dest).expect("create embedded_skills.rs");
    writeln!(
        f,
        "// @generated by build.rs — do not edit. {} embedded skill assets.",
        files.len()
    )
    .unwrap();
    writeln!(f, "pub static EMBEDDED: &[(&str, &[u8])] = &[").unwrap();
    for (rel, abs) in &files {
        // include_bytes! with an absolute path — no escaping of file contents needed.
        writeln!(
            f,
            "    ({:?}, include_bytes!({:?})),",
            rel,
            abs.to_string_lossy()
        )
        .unwrap();
    }
    writeln!(f, "];").unwrap();
}
