---
- name: Push KES certificate to block producer
  hosts: bp
  become: true
  gather_facts: false
  tasks:
    - name: Include KES push tasks
      ansible.builtin.include_role:
        name: cardano-node
        tasks_from: kes_push
