---
- name: Generate KES keypair on block producer
  hosts: bp
  become: true
  gather_facts: false
  tasks:
    - name: Include KES generate tasks
      ansible.builtin.include_role:
        name: cardano-node
        tasks_from: kes_generate
